services:
  _defaults:
    public: true

  mbo.accounts.data_provider:
    class: PrestaShop\Module\Mbo\Accounts\Provider\AccountsDataProvider
    arguments:
#      - '@prestashop.adapter.data_provider.module'
      - "5.2.5"
