services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Addons\User\AddonsUser:
    autowire: true
    autoconfigure: true

  PrestaShop\Module\Mbo\Addons\User\AddonsUserProvider:
    autowire: true
    autoconfigure: true

  PrestaShop\Module\Mbo\Addons\Provider\AddonsDataProvider:
    autowire: true
    properties:
      cacheDir: "%kernel.cache_dir%"

  # Addons API Client
  PrestaShop\Module\Mbo\Addons\ApiClient:
    autowire: true
    arguments:
      $apiUrl: "%env(ADDONS_API_URL)%"
      $httpClient: '@Psr\Http\Client\ClientInterface'
      $requestFactory: '@Psr\Http\Message\ServerRequestFactoryInterface'
    calls:
      - method: setDefaultParams
        arguments:
          - "@=service('translator').getLocale()"
          - "@=service('prestashop.adapter.data_provider.country').getIsoCodebyId()"
          - "@=service('prestashop.adapter.legacy.configuration').get('_PS_BASE_URL_')"
          - "@=service('prestashop.core.foundation.version').getSemVersion()"

  PrestaShop\Module\Mbo\Addons\Toolbar:
    autowire: true
