services:
  _defaults:
    public: true

  mbo.addon.module.repository:
    class: PrestaShop\Module\Mbo\Addons\Module\ModuleRepository
    arguments:
      - "@mbo.addon.module.data_provider.admin_module"
      - "@mbo.addon.module.data_prodiver.module"
      - "@prestashop.core.module.updater"
      - "@prestashop.adapter.legacy.logger"
      - "@translator"
      - "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"
      - "@doctrine.cache.provider"

  mbo.addon.module.data_provider.admin_module:
    class: PrestaShop\Module\Mbo\Addons\Module\AdminModuleDataProvider
    arguments:
      - "@translator"
      - "@logger"
      - "@mbo.addon.module.data_provider.addons"
      - "@prestashop.categories_provider"
      - "@mbo.addon.module.data_prodiver.module"
      - "@doctrine.cache.provider"
      - "@=service('prestashop.adapter.legacy.context').getContext().employee"
    calls:
      - [ setRouter, ['@router']]

  mbo.addon.module.data_prodiver.module:
    class: PrestaShop\Module\Mbo\Addons\Module\ModuleDataProvider
    arguments:
      - "@prestashop.adapter.legacy.logger"
      - "@translator"
      - "@doctrine.orm.entity_manager"
    calls:
      - [ "setEmployeeId", ["@=service('prestashop.adapter.legacy.context').getContext().employee?service('prestashop.adapter.legacy.context').getContext().employee.id:0"]]

  mbo.addon.module.data_provider.addons:
    class: PrestaShop\Module\Mbo\Addons\DataProvider
    arguments:
      - '@mbo.addon.client.api'
      - '@prestashop.module.zip.manager'
      - '@=service("prestashop.adapter.legacy.configuration").get("ADDONS_API_MODULE_CHANNEL", "stable")'
    properties:
      cacheDir: "%kernel.cache_dir%"

  mbo.addon.module.updater:
    class: PrestaShop\Module\Mbo\Addons\DataUpdater
    arguments:
      - "@mbo.addon.module.data_provider.addons"
      - "@mbo.addon.module.data_prodiver.module"

  mbo.addon.module.manager:
    class: PrestaShop\Module\Mbo\Addons\Module\ModuleManager
    arguments:
      - "@mbo.addon.module.data_provider.admin_module"
      - "@mbo.addon.module.data_prodiver.module"
      - "@mbo.addon.module.updater"
      - "@mbo.addon.module.repository"
      - "@prestashop.module.zip.manager"
      - "@translator"
      - "@event_dispatcher"
      - "@prestashop.adapter.cache.clearer.symfony_cache_clearer"

  # Addons API Client
  mbo.addon.client.api:
    class: PrestaShop\Module\Mbo\Addons\Service\ApiClient
    arguments:
      - "@eight_points_guzzle.client.addons_api"
      - "@=service('translator').getLocale()"
      - "@=service('prestashop.adapter.data_provider.country').getIsoCodebyId()"
      - "@=service('prestashop.adapter.legacy.configuration').get('_PS_BASE_URL_')"
      - "@=service('prestashop.core.foundation.version').getVersion()"
