imports:
  - { resource: api/security.yml }
  - { resource: api/repository.yml }
  - { resource: api/service.yml }
  - { resource: api/context.yml }

services:
  ps_mbo.db:
    class: Db
    public: true
    factory: [ 'Db', 'getInstance' ]

  ps_mbo:
    class: 'ps_mbo'
    public: true
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'ps_mbo'

  PrestaShop\Module\Mbo\Api\Config\Env:
    class: PrestaShop\Module\Mbo\Api\Config\Env

  PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandlerInterface: '@PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandler'

  PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandler:
    class: PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandler
    public: true
    arguments:
      - '@ps_mbo'
      - '@PrestaShop\Module\Mbo\Api\Config\Env'
