imports:
  - { resource: api/repository.yml }

services:
  _defaults:
    public: true

  ps_mbo.db:
    class: Db
    factory: [ 'Db', 'getInstance' ]

  ps_mbo:
    class: 'ps_mbo'
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'ps_mbo'

  PrestaShop\Module\Mbo\Api\Config\Env:
    autowire: true

  PrestaShop\Module\Mbo\Api\Service\ModuleTransitionExecutor:
    autowire: true

  PrestaShop\Module\Mbo\Api\Service\ConfigApplyExecutor:
    autowire: true

  PrestaShop\Module\Mbo\Api\Service\Factory:
    autowire: true
    arguments:
      - [
          '@PrestaShop\Module\Mbo\Api\Service\ModuleTransitionExecutor',
          '@PrestaShop\Module\Mbo\Api\Service\ConfigApplyExecutor'
      ]
