services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Service\ModuleInstaller:
    autowire: true
    arguments:
      - "ps_eventbus"

  mbo.ps_eventbus.installer:
    alias: PrestaShop\Module\Mbo\Service\ModuleInstaller