services:
  _defaults:
    public: true

  mbo.ps_eventbus.installer:
    class: 'PrestaShop\Module\Mbo\Service\ModuleInstaller'
    public: true
    arguments:
      - "ps_eventbus"
      - "3.0.8"
      - false