---
services:
  _defaults:
    public: true

  mbo.module.repository:
    class: PrestaShop\Module\Mbo\Module\Repository
    arguments:
      - "@mbo.addon.client.api"
      - "@translator"
      - "@logger"
      - "@doctrine.cache.provider"

  mbo.module.filter:
    class: PrestaShop\Module\Mbo\Module\Filter

  mbo.module.collection.factory:
    class: PrestaShop\Module\Mbo\Module\CollectionFactory
