---
services:
  _defaults:
    public: true

  mbo.modules.repository:
    class: PrestaShop\Module\Mbo\Module\Repository
    arguments:
      - "@mbo.cdc.client.connected_distribution_api"
      - "@mbo.modules.builder"
      - "@logger"
      - "@=service('translator').getLocale()"
      - "@doctrine.cache.provider"
      - "@=service('prestashop.adapter.legacy.configuration').get('_DB_PREFIX_')"
      - "@mbo.security.admin_authentication.provider"

  mbo.modules.filters.factory:
    class: PrestaShop\Module\Mbo\Module\FiltersFactory

  mbo.modules.collection.factory:
    class: PrestaShop\Module\Mbo\Module\CollectionFactory

  mbo.modules.builder:
    class: PrestaShop\Module\Mbo\Module\ModuleBuilder
    arguments:
      - '@router'
      - "@logger"
      - "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"

  mbo.modules.files_manager:
    class: PrestaShop\Module\Mbo\Module\FilesManager
    arguments:
      - '@mbo.addons.data_provider'
      - '@prestashop.module.factory.sourcehandler'

  mbo.modules.actions_manager:
    class: PrestaShop\Module\Mbo\Module\ActionsManager
    arguments:
      - '@mbo.modules.files_manager'
      - '@mbo.modules.repository'
      - '@mbo.modules.state_machine.source_retriever.url'
