---
services:
  _defaults:
    public: true

  mbo.modules.repository:
    class: PrestaShop\Module\Mbo\Module\Repository
    arguments:
      - "@mbo.addons.data_provider"
      - "@mbo.modules.builder"
      - "@logger"
      - "@=service('translator').getLocale()"
      - "@doctrine.cache.provider"
      - "@=service('prestashop.adapter.legacy.configuration').get('_DB_PREFIX_')"

  mbo.modules.filters.factory:
    class: PrestaShop\Module\Mbo\Module\FiltersFactory

  mbo.modules.collection.factory:
    class: PrestaShop\Module\Mbo\Module\CollectionFactory

  mbo.modules.builder:
    class: PrestaShop\Module\Mbo\Module\ModuleBuilder
    arguments:
      - '@router'
      - "@logger"
      - "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"
