services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Api\Security\AdminAuthenticationProvider:
    class: PrestaShop\Module\Mbo\Api\Security\AdminAuthenticationProvider
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@prestashop.core.crypto.hashing'
      - '@prestashop.adapter.legacy.context'

  PrestaShop\Module\Mbo\Api\Security\AuthorizationChecker:
    class: PrestaShop\Module\Mbo\Api\Security\AuthorizationChecker
    arguments:
      - '@doctrine.cache.provider'
      - '@mbo.cdc.client.nest_api'

  mbo.security.permission_checker:
    class: PrestaShop\Module\Mbo\Security\PermissionChecker
    arguments:
      - '@prestashop.adapter.legacy.context'
