services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Tab\TabCollectionFactoryInterface: '@PrestaShop\Module\Mbo\Tab\TabCollectionFactory'

  PrestaShop\Module\Mbo\Tab\TabCollectionFactory:
    autowire: true

  PrestaShop\Module\Mbo\Tab\TabCollectionProviderInterface: '@PrestaShop\Module\Mbo\Tab\TabCollectionProvider'

  PrestaShop\Module\Mbo\Tab\TabCollectionProvider:
    autowire: true
