preserve_hierarchy: 
commit_message: 'fix: New (%language%) translations'
append_commit_message: 
pull_request_title: 'Update translations for language : %locale%'
pull_request_labels:
  - translations
files:
  - source: /translations/*/*.en-US.xlf
    translation: '%file_name%.%locale%.%file_extension%'
    type: xliff
    translation_replace:
      en-US.: ''
