preserve_hierarchy: true
commit_message: 'fix: New (%language%) translations'
append_commit_message: false
pull_request_title: 'Update translations for language : (%language%)'
pull_request_labels:
  - translations
files:
  - source: /translations/en-US/*.xlf
    dest: module.php
    translation: /translations/%locale%/%original_file_name%
    type: xliff
    labels:
      - ps_mbo
      - module