preserve_hierarchy: 
commit_message: 'fix: New (%language%) translations'
append_commit_message: 
pull_request_title: 'Update translations for language : %locale%'
pull_request_labels:
  - translations
files:
  - source: /translations/*/*.en-US.xlf
    translation: %original_file_name%
    translation_replace:
      "en-US.": ""
    type: xliff
    labels:
      - translations
