services:
  _defaults:
    public: true

  mbo.handlers.query.get_modules_for_listing_handler:
    class: 'PrestaShop\Module\Mbo\Module\QueryHandler\GetModulesForListingHandler'
    arguments:
      - '@mbo.modules.filters.factory'
      - '@mbo.modules.collection.factory'
      - '@mbo.modules.repository'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\Module\Mbo\Module\Query\GetModulesForListing'
