---
api_mbo_module_action:
  path: /module-actions
  methods: [GET]
  defaults:
    _controller: mbo.controller.api.module_action:indexAction
#    _legacy_controller: apiPsMbo
#    controller: 'apiPsMbo'
