admin_mbo_recommended_modules:
  path: /
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleRecommendedController::indexAction'
    _legacy_controller: AdminPsMboRecommended
    _legacy_link: AdminPsMboRecommended
