admin_mbo_recommended_modules:
  path: /
  methods: [GET]
  defaults:
    _controller: mbo.controller.modules.recommended:indexAction
    _legacy_controller: AdminPsMboRecommended
    _legacy_link: AdminPsMboRecommended
