admin_mbo_catalog_theme:
  path: /
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ThemeCatalogController::indexAction'
    _legacy_controller: AdminPsMboTheme
    _legacy_link: AdminPsMboTheme
