services:
  _defaults:
    public: true

  ps_mbo.context:
    class: 'Context'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getContext']

  ps_mbo.controller:
    class: 'Controller'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getController']

  ps_mbo.cookie:
    class: 'Cookie'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getCookie']

  ps_mbo.language:
    class: 'Language'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getLanguage']

  ps_mbo.currency:
    class: 'Currency'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getCurrency']

  ps_mbo.smarty:
    class: 'Smarty'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getSmarty']

  ps_mbo.shop:
    class: 'Shop'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getShop']

  ps_mbo.link:
    class: 'Link'
    factory: ['PrestaShop\Module\Mbo\Api\Factory\ContextFactory', 'getLink']