services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Api\Security\AdminAuthenticationProvider:
    class: PrestaShop\Module\Mbo\Api\Security\AdminAuthenticationProvider
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
