services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Api\Security\KMSClientInterface: '@PrestaShop\Module\Mbo\Api\Security\KMSClient'

  PrestaShop\Module\Mbo\Api\Security\KMSClient:
    class: PrestaShop\Module\Mbo\Api\Security\KMSClient
    arguments:
      - '%env(GOOGLE_APPLICATION_PROJECT)%'
      - '%env(GOOGLE_APPLICATION_PROJECT_DEFAULT_LOCATION)%'
      - '%env(GOOGLE_APPLICATION_KEY_RING)%'

  PrestaShop\Module\Mbo\Api\Security\KeyProvider:
    class: PrestaShop\Module\Mbo\Api\Security\KeyProvider
    arguments:
      - '@PrestaShop\Module\Mbo\Api\Security\KMSClientInterface'
