name: Install module on MyDemoShop
on:
  workflow_run:
    workflows:
      - "Install Module on Shop"
    types:
      - completed

jobs:
  install_module:
    name: Install ps_mbo module
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'install')
    steps:
      - name: Get label infos
        id: get_label_infos
        run: |
          label=$(echo '${{ tojson(github.event.pull_request.labels) }}' | jq -r '.[].name | select(. | contains("install"))')
          echo $label
          demo=$(echo $label | awk -F/ '{print $2}')
          name=$(echo $label | awk -F/ '{print $3}')
          echo $demo
          echo $name
          echo """demo=$(echo $demo)""" >> $GITHUB_OUTPUT
          echo """name=$(echo $name)""" >> $GITHUB_OUTPUT

      - name: Get the download url of the latest artifacts uploaded
        id: get_latest_artifact
        run: |
          url=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts --jq '.artifacts[0].archive_download_url')
          echo """url=$(echo $url)""" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Install Prestashop module on MyDemoShop
        uses: PrestaShopCorp/github-action-install-module-mydemoshop@main
        with:
          environment: "demo-${{ steps.get_label_infos.outputs.demo }}"
          shop_name: ${{ steps.get_label_infos.outputs.name }}
          module_name: ps_mbo
          module_zip_url: ${{ steps.get_latest_artifact.outputs.url }}
        env:
          GOOGLE_APIS_CLIENT_ID: ${{ secrets.GOOGLE_APIS_CLIENT_ID }}
          GOOGLE_APIS_CLIENT_SECRET: ${{ secrets.GOOGLE_APIS_CLIENT_SECRET }}
          GOOGLE_APIS_REFRESH_TOKEN: ${{ secrets.GOOGLE_APIS_REFRESH_TOKEN }}
          INSTALL_MODULE_MYDEMOSHOP_URL: ${{ secrets.INSTALL_MODULE_MYDEMOSHOP_URL }}
