name: Publish TechDocs Site

on:
  workflow_dispatch:
  push:
    branches: [feat/catalog-info]

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCS_BUCKET_NAME: ps-eu-w1-backstage-documentations-integration
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'ps_mbo-documentation'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth GCP
        uses: PrestaShopCorp/prestashop-github-action-gcp-auth@v1
        with:
          auth-mode: 'workload-federation' # ou 'json-file'
          provider: ${{ secrets.WI_PROVIDER_INTEGRATION }}
          service-account: ${{ secrets.WI_SA_INTEGRATION }}
          setup-gcloud: false
          registry-login: false

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type googleGcs --storage-name $GCS_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME